version: 1
formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
loggers:
  sudoku_ai:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: WARNING
  handlers: [console]